FROM python:3.10.1-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && apt-get install -y iputils-ping
RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# COPY .streamlit/config.toml ~/.streamlit/config.toml

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://streamlit:8501/_stcore/health


CMD streamlit run Home.py --theme.base="dark"