from dotenv import dotenv_values

config = {**dotenv_values(".env_API")}

SECRET_KEY = config['SECRET_KEY']
ALGORITHM = config['ALGORITHM']
ACCESS_TOKEN_EXPIRE_MINUTES = config['ACCESS_TOKEN_EXPIRE_MINUTES']
WEATHER_API_KEY = config['WEATHER_API_KEY']

DB_ENV = config['DB_ENV']

USER_SNOWFLAKE      = config['USER_SNOWFLAKE']
PWD_SNOWFLAKE       = config['PWD_SNOWFLAKE']
ACCOUNT_SNOWFLAKE   = config['ACCOUNT_SNOWFLAKE']
WAREHOUSE_SNOWFLAKE = config['WAREHOUSE_SNOWFLAKE']
DB_SNOWFLAKE        = config['DB_SNOWFLAKE']
SCHEMA_SNOWFLAKE    = config['SCHEMA_SNOWFLAKE']

DB_MYSQL_HOST    = config['DB_MYSQL_HOST']
DB_MYSQL_DBNAME  = config['DB_MYSQL_DBNAME']
DB_MYSQL_USER    = config['DB_MYSQL_USER']
DB_MYSQL_USR_PWD = config['DB_MYSQL_USR_PWD']